### PR TITLE
Remove all $.each calls

### PR DESCRIPTION
**Pull request by nitriques**
Replace them with native calls, which are way better and leads to
cleaner code

### CODE REVIEW

**Comment by nitriques** [comment]
@fhamon The goal is to drop, but those are easy to polyfill in case a client wants to pay for IE. But by default, no polyfill.

**Comment by fhamon** [comment]
@nitriques :partyparot:

**Comment by nitriques** [comment]
@PascalPiche @dominic-blain @fhamon I've rebased it!

**Comment by nitriques** [comment]
@DeuxHuitHuit/review ping

**Pull request merged**
